### ISSUE TITLE
Searching fails. Missing isRounded method

### ISSUE THREAD

**Issue by Sinnbeck** [InfinetyEs/Nova-Filemanager#101]
Just installed your package using Nova 2.7
Searching causes this error
>Method Infinety\Filemanager\FilemanagerField::isRounded does not exist.

I expect it is caused by changes in /src/Fields/Image.php and ResolvesField::resolveIfAvatarShouldBeRounded

**Comment by Krato** [comment]
Thanks for the issue. We'll fix soon.

**Comment by Krato** [comment]
Hello @Sinnbeck and @webteamseo. Should be fixed in [v2.6](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.6). Check it

**Comment by Sinnbeck** [comment]
@Krato Yes that seems to have solved it indeed :)

**Comment by webteamseo** [comment]
Thank you very much for the fix :)
