### ISSUE TITLE
Can upload any file but not create folders 

### ISSUE THREAD

**Issue by keganlester** [InfinetyEs/Nova-Filemanager#104]
Hello,

Love the package so far but I think I might have found a bug. 

When trying to edit or create a folder I get this error.

`iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT//IGNORE' is not allowed`

Other than the folders this package works great!

last 5 stacks

`0: {function: "handleError", class: "Illuminate\Foundation\Bootstrap\HandleExceptions", type: "->"}
class: "Illuminate\Foundation\Bootstrap\HandleExceptions"
function: "handleError"
type: "->"
1: {file: "/var/www/html/vendor/infinety-es/nova-filemanager/src/Http/Services/FileFunctions.php",…}
file: "/var/www/html/vendor/infinety-es/nova-filemanager/src/Http/Services/FileFunctions.php"
function: "iconv"
line: 62
2: {file: "/var/www/html/vendor/infinety-es/nova-filemanager/src/Http/Services/FileManagerService.php",…}
class: "Infinety\Filemanager\Http\Services\FileManagerService"
file: "/var/www/html/vendor/infinety-es/nova-filemanager/src/Http/Services/FileManagerService.php"
function: "fixFilename"
line: 147
type: "->"
3: {,…}
class: "Infinety\Filemanager\Http\Services\FileManagerService"
file: "/var/www/html/vendor/infinety-es/nova-filemanager/src/Http/Controllers/FilemanagerToolController.php"
function: "createFolderOnPath"
line: 48
type: "->"
4: {function: "createFolder", class: "Infinety\Filemanager\Http\Controllers\FilemanagerToolController",…}
class: "Infinety\Filemanager\Http\Controllers\FilemanagerToolController"
function: "createFolder"
type: "->"`

**Comment by Krato** [comment]
Hi @keganlester. Have you check if iconv php extension is activated? Regards
