### ISSUE TITLE
Config maxFileSize or permissions

### ISSUE THREAD

**Issue by keganlester** [InfinetyEs/Nova-Filemanager#105]
Uploading a photo of 496kb and it says the file is too large. Where is there config to up this?

**Comment by keganlester** [comment]
It is uploading but you aren't displaying it because you have a fixed file-size of 350kb. This should be editable by the user.

**Comment by Krato** [comment]
@keganlester You can increase your php max file size by your self. Check https://stackoverflow.com/a/2184541

An you can use Laravel rules to limit the size.
