### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by inodesrl** [InfinetyEs/Nova-Filemanager#106]
For me  it would be necessary a link for the direct download of the files (in modal view or in grid/list view)
Thanks, Marco.

**Comment by Krato** [comment]
Feel free to open a PR

**Comment by JulianMar** [comment]
I opened a PR for this feature. Checkout #128

**Comment by Krato** [comment]
Yes. Merged on v2.8

**Comment by inodesrl** [comment]
thanks
