### ISSUE TITLE
Little bug when uploading a folder inside of another folder

### ISSUE THREAD

**Issue by victorlap** [InfinetyEs/Nova-Filemanager#107]
If you are in a folder, and then drag + drop a folder into the window, the path at which the files are uploaded is not correct.

I believe the fix is in the following line:
https://github.com/InfinetyEs/Nova-Filemanager/blob/master/resources/js/components/UploadProgress.vue#L134
If you add a `/` between `this.current` and `filePath`, the naming should work correctly

See also the attached screenshots. For the demo, I uploaded the following folder structure twice: `/test/sub/sub2/`
<img width="543" alt="Screen Shot 2019-11-26 at 2 58 05 PM" src="https://user-images.githubusercontent.com/1645632/69639727-56a6db00-105d-11ea-8b9d-175656be9bac.png">
<img width="375" alt="Screen Shot 2019-11-26 at 2 58 31 PM" src="https://user-images.githubusercontent.com/1645632/69639728-56a6db00-105d-11ea-8d79-093df37d210f.png">

**Comment by Krato** [comment]
Fixed on [v2.6.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.6.5)
