### ISSUE TITLE
Select multiple images

### ISSUE THREAD

**Issue by mdixon18** [InfinetyES/Nova-Filemanager#11]
Say you have a slider and you need the ability to add multiple images, is there a way to do this currently? Or make it repeatable?

**Comment by Krato** [comment]
This should be another field yes? This is only a filemanager. 

Maybe you can use these packages:

https://novapackages.com/packages/64robots/nova-row
https://novapackages.com/packages/fourstacks/nova-repeatable-fields


Regards

**Comment by mdixon18** [comment]
Yeah this is great thanks.
