### ISSUE TITLE
Remove file is still present on modal although delete file button is disabled

### ISSUE THREAD

**Issue by FrittenKeeZ** [InfinetyEs/Nova-Filemanager#110]
You currently can't prevent users from deleting files, as "Remove File" is present on the file modal, and allows for file deletion, although delete file button is disabled.

```php
'buttons'   => [

    // Menu
    'create_folder'   => false,
    'upload_button'   => false,
    'select_multiple' => false,

    // Folders
    'rename_folder'   => false,
    'delete_folder'   => false,

    // Files
    'rename_file'     => false,
    'delete_file'     => false,

],
```

We want to use filemanager as readonly, so is it possible to have "Remove File" disabled as well?

**Comment by Krato** [comment]
Yes @FrittenKeeZ. Fixed in [v2.6.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.6.5)
