### ISSUE TITLE
Markdown editor integration

### ISSUE THREAD

**Issue by royduin** [InfinetyEs/Nova-Filemanager#111]
It would be nice to have an integration with the Nova Markdown editor field. Currently the image button of the Markdown field pastes `![](http://)` into the content, having that replaced with the filemanager popup like the FilemanagerField does would be nice. After selecting an image it will be inserted like `![image](http://url-to-the-image.jpg)`

**Comment by Krato** [comment]
Hello @royduin. This would be cool. But should be related to the markdown field. No options to do this for now.

Regards
