### ISSUE TITLE
Filters break when used with Nova Flexible Content

### ISSUE THREAD

**Issue by stevelacey** [InfinetyEs/Nova-Filemanager#116]
I don't know if the problem is in https://github.com/whitecube/nova-flexible-content or in this package but the filters stop working when the file manager is used within a flexible content area – primarily this means users can select non-images in fields that I meant to only be images.

As far as I can see everything else is fine. Any idea what's up? I'll submit a PR if I can work it out.

**Comment by Krato** [comment]
Hey, I haven't tried our Filemanager with that package. Any error logs?

**Comment by stevelacey** [comment]
Nothing by default in the js console, `$this->filterBy('images')` just has no effect, I can only assume the prop is not getting set or something.

I tried to compile Nova with `yarn && npm run dev` so I could get Vue dev tools on, but that didn't seem to work – I did get some console warnings though which might be related:

```
[portal-vue]: source Modal FileManager already exists
[portal-vue]: source File Details already exists
[portal-vue]: source Remove File already exists
[portal-vue]: source Deselect File already exists
[portal-vue]: source Modal FileManager already exists
[portal-vue]: source File Details already exists
[portal-vue]: source Remove File already exists
[portal-vue]: source Deselect File already exists
[portal-vue]: source Modal FileManager already exists
[portal-vue]: source File Details already exists
[portal-vue]: source Remove File already exists
[portal-vue]: source Deselect File already exists
```

Perhaps some unique keys are needed or something

**Comment by Krato** [comment]
Try this to get VueTools: https://gist.github.com/Krato/b3f5891b917dadeb696b4aa36dda06d4

**Comment by stevelacey** [comment]
The problem is here: https://github.com/OpenUpMusic/OOO/blob/master/vendor/infinety-es/nova-filemanager/src/Http/Controllers/FilemanagerToolController.php#L123-L139

I don't think you can rely on `$field->attribute` matching for this if you want to support any libraries doing anything like flexible content.

The attribute is prefixed (derived from FlexibleAttribute) in the case of Nova Flexible Content, with a random string + `__` then the friendly name, so that it they're unique in repeating blocks.

I suspect the correct thing to do is to always pass the full set of `filters` through from the config to the js, and have the component(s) filter that list by `filterBy`, and/or pass the `filterBy` explicitly in the `getData` call via a query param, rather than attempting to retrieve it from the field via this loop.

**Comment by stevelacey** [comment]
I think I've fixed it, PR soon 🙌 I've abandoned that loop and switched to passing `&filter=` instead, seems to work consistently everywhere
