### ISSUE TITLE
Relation modal with FilemanagerField

### ISSUE THREAD

**Issue by Mopsit** [InfinetyEs/Nova-Filemanager#127]
I have a resource with a relation to another resource containing a FilemanagerField. When I click +Create to create a new resource of the relation, a Modal pops up, which works fine, but when I click "Open Filemanager" on the relation modal, it closes and reopens the modal instead of showing filemanager.

Is it impossible to make something to have this work?

[Create button](https://i.gyazo.com/1d07f72f8fdb0b3fdb4b96289c7f9019.png)
[Modal](https://i.gyazo.com/b0dd8cc8e1fdd37db8a074e1e2cd39ae.png)

**Comment by Krato** [comment]
We have an still issue referenced #73
