### ISSUE TITLE
Sort by "last modification" file property

### ISSUE THREAD

**Issue by Azomas** [InfinetyEs/Nova-Filemanager#130]
I see that files can be sorted by name, mime and size.
It would be very convenient to add one more property to this list - file date

**Comment by Azomas** [comment]
I wish to help add this feature, though I probably will need some guidance.

**Comment by Krato** [comment]
@Azomas You can set the order to `last_modification` and files will be ordered by last modification.

Regards

**Comment by aliwesome** [comment]
@Krato where exactly should I set the order?

**Comment by aliwesome** [comment]
> @Krato where exactly should I set the order?

I had found that, in config file set `FILEMANAGER_ORDER` to  `last_modification` as Krato said.
