### ISSUE TITLE
Error reading the folder. Please check your logs.

### ISSUE THREAD

**Issue by vwasteels** [InfinetyEs/Nova-Filemanager#139]
I know there is already 2 issues with same title, but I have no more information, I checked in `./storage/logs/laravel.log` and in my ngynx logs , nothing shows , nothing in the console neither , 

I'm using latest Nova `3.6.0`
with latest Nova-Filemanger `2.8.1`

Any though on how to debug this ?
thank you

**Comment by Krato** [comment]
No way to test this without any log or screenshot.
