### ISSUE TITLE
Allow multiple file field

### ISSUE THREAD

**Issue by breizhwave** [InfinetyEs/Nova-Filemanager#140]
Hi, which would you recommend to implement multiple file field with description / tags 

https://novapackages.com/packages/whitecube/nova-flexible-content
or 
https://novapackages.com/packages/fourstacks/nova-repeatable-fields

have you tested any of the two ? 

second bonus question : possibility of using tags package with files in the file explorer  ? thks

**Comment by breizhwave** [comment]
Hi FYI just tested https://novapackages.com/packages/whitecube/nova-flexible-content

works like a charm

**Comment by Krato** [comment]
**First question**:

Yes should work with both.

**Second question**:

This isn’t in our futures changes. 


Regards!
