### ISSUE TITLE
Can't remove the image from field

### ISSUE THREAD

**Issue by bcoelhonqda** [InfinetyES/Nova-Filemanager#16]
After insert an image, i can't remove from field.
The only option i have is delete the image from FileManager.

Screenshots:
http://www.clipular.com/posts/5827487813337088?k=5_5YKF7MDfGD8bPy1-mHvyL3J8M
http://www.clipular.com/posts/4505571471130624?k=5IAZpB8P9O9fv6K1lrz_aL7Ebs0

**Comment by Krato** [comment]
Yes not yet. You can remove it from the tools instead.

Maybe in the next release.

Thanks!

**Comment by Krato** [comment]
@bcoelhonqda try the new v1.1.1 release.
Regards
