### ISSUE TITLE
S3 Filesystem cache

### ISSUE THREAD

**Issue by tjmckenzie** [InfinetyES/Nova-Filemanager#18]
When enabling the cache directive of the s3 filesystem config, as described [here](https://laravel.com/docs/5.6/filesystem#caching), File Manager does not properly load. 

`GET .../nova-vendor/infinety-es/nova-filemanager/data?folder=%2F 500 (Internal Server Error)`
`Call to undefined method League\Flysystem\Cached\CachedAdapter::getPathPrefix()`

**Comment by Krato** [comment]
@tjmckenzie Thanks for your issue. I will check it

**Comment by Krato** [comment]
@tjmckenzie It seems a problem with Flysystem Cache adapter. But is working following next guide. Can you try it? https://medium.com/@poweredlocal/caching-s3-metadata-requests-in-laravel-bb2b651f18f3

Regards

**Comment by tjmckenzie** [comment]
After a quick attempt late last night, I wans't able to get this method working either. Laravel docs seem to be lacking on cache implementation for filesystem. I'll do some source diving this evening and give it another try.

**Comment by Krato** [comment]
@tjmckenzie I was able to work with the link above from medium. Have you tried that?

**Comment by tjmckenzie** [comment]
I have tried that, but was unable to get it working. Can you provide a gist of how you had it set up?

It seems if I set the s3->driver setting to `s3-cached` service provider, with or without adding the ` cache directive` to the s3 config as described in the laravel docs, I still get the same error. 

However, without enabling the cache, the nova media manager seems to load much after after the initial load, so some sort of caching is already in action. This is good enough for me, at this time.
