### ISSUE TITLE
Bad thumb path

### ISSUE THREAD

**Issue by JILeXanDR** [InfinetyEs/Nova-Filemanager#19]
Should add documentation for this config https://github.com/InfinetyES/Nova-Filemanager/blob/e0c8bb7745422bcf837769ce92ede45c4e6226a4/src/Http/Services/GetFiles.php#L374-L381
because it returns false and makes bad link

**Comment by Krato** [comment]
Thanks @JILeXanDR. Let me check it. Regards!

**Comment by Krato** [comment]
@JILeXanDR Changed in the last release. This config is not used anymore.

**Comment by JILeXanDR** [comment]
@Krato The bug is remained =(

I have disk called `img`:
```
// filesystems.php
'img' => [
    'driver' => 'local',
    'root' => public_path('assets/img'),
    'url' => env('ADMIN_URL') . '/assets/img',
    'visibility' => 'public',
],
```

```
// .env
FILEMANAGER_DISK=img
```

The full link should be `http://admin.host.local/assets/img/avatars/1.jpg`
but ajax `/data?folder=avatars` generates another with `storage`:
`http://admin.host.local/storage/1.jpg`

The problem is in https://github.com/InfinetyES/Nova-Filemanager/blob/856b24dc5d512d0a22b9bbedc3d37a6d51ac1183/src/Http/Services/GetFiles.php#L215-L221

**Comment by Krato** [comment]
Ok. I will take a look. Thanks

**Comment by ianmcqueen** [comment]
@Krato I am also experiencing this bug (broken thumbnail) for the following file system configuration:

`
// config/filesystems.php
        'uploads' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'url' => env('APP_URL').'/uploads',
            'visibility' => 'public',
        ],
`

The thumbnail URL is displaying as `style="background-image: url("/storage/ffq-newquest.jpg");"` when it should be using `url` from the file system configuration (uploads).

**Comment by Krato** [comment]
Hello @JILeXanDR and @ianmcqueen. Please, update to v2. Should be fixed. Regards.
