### ISSUE TITLE
Add posibility to set default folder

### ISSUE THREAD

**Issue by JILeXanDR** [InfinetyES/Nova-Filemanager#21]
Usage example:

    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            FilemanagerField::make('Avatar', 'avatar_path')->folder('avatars'),
        ];
    }

It makes find images easier.

**Comment by Krato** [comment]
Thats a good idea. Maybe in the next release.

**Comment by Krato** [comment]
@JILeXanDR CHeck the new v1.1.1 release. Folder option is done
