### ISSUE TITLE
Specify visibility?

### ISSUE THREAD

**Issue by christopherarter** [InfinetyEs/Nova-Filemanager#26]
Hi there,

Great package!

Question: Is there a way to specify the visibility when saving a file? e.g. 
`Storage::put('file.jpg', $contents, 'public');`

I notice it looks like it's defaulted to public here:
[https://github.com/InfinetyES/Nova-Filemanager/blob/f7176a2e6f2148d174533dc91f3bbc4551db23e5/src/Http/Services/FileManagerService.php#L222](https://github.com/InfinetyES/Nova-Filemanager/blob/f7176a2e6f2148d174533dc91f3bbc4551db23e5/src/Http/Services/FileManagerService.php#L222)

Thank you!

**Comment by lwiml** [comment]
Do you have any solution yet, or workaround?

**Comment by lwiml** [comment]
Do you have any solution yet, or workaround?

**Comment by christopherarter** [comment]
@lwiml Not quite, I ended up having to edit that method, setting the default to private. Then, if I wanted to show a file publicly I used [signed Urls](https://laravel.com/docs/5.7/urls#signed-urls) to authorize the file to be accessed.

**Comment by lwiml** [comment]
@christopherarter thanks, but ofcourse it's not ideal.

**Comment by Krato** [comment]
Hi @christopherarter. Not yet. May be in the future

**Comment by Krato** [comment]
Hello @christopherarter. You can set he visibility now with v2. Please check the readme. Regards
