### ISSUE TITLE
Access control, "Home"

### ISSUE THREAD

**Issue by tanthammar** [InfinetyEs/Nova-Filemanager#28]
Is there a way to disable the "Home" link in the field modal or,
can I dynamically set the home path to equal the $folder parameter?

My app creates a storage folder per "team", inside the File Manager Disk path.
I would like to set this folder as Storage::disk() so it becomes the "home" path for that user.
As it is now, I can set the initial view to the teams storage path, but the "Home" link gives the user access to all other team folders.

````
$folder = $request->user()->team_storage();
        return [
            FilemanagerField::make('Images')
            ->displayAsImage()
            ->folder($folder)
        ];
```

**Comment by Krato** [comment]
Hi @tanthammar. Will work in that issue. Thanks

**Comment by Krato** [comment]
Hello @tanthammar. Now works like should work. When you set the folder, this folder will be the home.
Check version 2. 

Regards.
