### ISSUE TITLE
Is it possible to restrict the returned list of files based on $user->id?

### ISSUE THREAD

**Issue by 949mac** [InfinetyEs/Nova-Filemanager#33]
I only want my users to access the files they upload. Is this possible?

**Comment by JoshuaBedford** [comment]
This would be a very useful feature! That as well as an admin being able to choose who has access to what files.

**Comment by wa7eedem** [comment]
it's will be nice if I can set the ID : `$user->id` OR `$company->id` !!

**Comment by Krato** [comment]
Isn't planned for now. Maybe in the future, but we not thinking in that.
