### ISSUE TITLE
Thumbnail pointing to local disk even using digital ocean

### ISSUE THREAD

**Issue by encomienda** [InfinetyEs/Nova-Filemanager#35]
The uploading and listing all fine but the thumbnail on the file manager seems pointing the local disk

![image](https://user-images.githubusercontent.com/26597108/52324822-bde79600-2a1d-11e9-9fca-20d94fd1548c.png)

![image](https://user-images.githubusercontent.com/26597108/52325316-8aa60680-2a1f-11e9-9f4b-966161dd2d8c.png)

**Comment by encomienda** [comment]
![image](https://user-images.githubusercontent.com/26597108/52325308-8548bc00-2a1f-11e9-8a31-1a9f6e007e0c.png)

**Comment by Krato** [comment]
@encomienda is now fixed. Please update to v2. Regards
