### ISSUE TITLE
Make translations publishable

### ISSUE THREAD

**Issue by markwalet** [InfinetyEs/Nova-Filemanager#38]
To make the package look more like Laravel Nova, I want to propose the following changes.

- Add a `resources/lang/en.json` file with all translation keys that are used. (The one in the readme are out of date)
- Load them and make them publishable via the service provider.
- Remove the translation keys from the readme.
- Add a tutorial on how to publish the translation files.

I already started working on a PR for this issue.

**Comment by Krato** [comment]
Hello @markwalet. I just revert your pull request. For now is not able to load translations into nova: https://github.com/laravel/nova-issues/issues/982

**Comment by aliwesome** [comment]
@Krato I think that problem is fixed now. can we have that PR merged?
