### ISSUE TITLE
If the image is very high, it does not allow to close the modal

### ISSUE THREAD

**Issue by sabid** [InfinetyES/Nova-Filemanager#4]
![screen shot 2018-08-31 at 3 30 13 pm](https://user-images.githubusercontent.com/3129855/44936767-3f325280-ad33-11e8-9ade-a46ee4902d21.png)

**Comment by Krato** [comment]
Yes. Thanks for your issue. Can you create a fix. If not, I will fix this weekend.

Thanks!

**Comment by InfinetyES** [comment]
Fixed! https://github.com/InfinetyES/Nova-Filemanager/pull/5
