### ISSUE TITLE
Add custome css 

### ISSUE THREAD

**Issue by sharmaanil8866** [InfinetyEs/Nova-Filemanager#40]
hello 

FilemanagerField::make('logo')
                ->displayAsImage()->folder('vendor_logo/'.date('Y_m_d'))
            ])
            

i have use this for show image but i add my custome class ??

**Comment by sharmaanil8866** [comment]
hello 


FilemanagerField::make('logo')
                ->displayAsImage()->folder('vendor_logo/'.date('Y_m_d'))
            ])
            

i have use this for show image but i add my custome class ??

**Comment by Krato** [comment]
What do you mean?
