### ISSUE TITLE
Filenames

### ISSUE THREAD

**Issue by fedeisas** [InfinetyEs/Nova-Filemanager#44]
Is there any way to customize filenames?

I see `FileManagerService::checkFileExists` takes care of that, but is there any easy way to override this?

Maybe we can set a callback in the Tool itself.

**Comment by Krato** [comment]
In the last version you can rename your files. Is what you want?

**Comment by fedeisas** [comment]
No, I mean before uploading, instead of using the original file name. My goal is to have lowercase file names, but I can imagine the user where you’d want to remove file names and use hashes.

**Comment by Krato** [comment]
Ahh Ok. Let me check it next week. Good idea 👌🏽

**Comment by fedeisas** [comment]
I’m more than happy to submit a PR if you give some hints on how you’d like to do it.

**Comment by Krato** [comment]
That's will be great. You can create an interface and a class with a funcion that recieves the name and returns a string. 

Then an option in the config file to use that class.

Something like: https://docs.spatie.be/laravel-backup/v6/monitoring-the-health-of-all-backups/creating-your-custom-health-check

Let me know if you understand.

**Comment by Krato** [comment]
@fedeisas Works perfect. Thanks for make this package greater. 👍 😃
