### ISSUE TITLE
file manager page is blank

### ISSUE THREAD

**Issue by jafar690** [InfinetyEs/Nova-Filemanager#47]
![Screenshot from 2019-04-01 08-25-52](https://user-images.githubusercontent.com/17546030/55305197-f8871100-5457-11e9-89d6-bdb8ece66219.png)

when i visit the file manager page, i get a blank page with the above error in the console

**Comment by Krato** [comment]
Hello @jafar690. Have you followed all the steps of the installation?

**Comment by jafar690** [comment]
@jafar690 Hello? yes i did, but its still not working, am using nova v 1.3.0

**Comment by Krato** [comment]
Hello @jafar690. Just tried with an empty installation with Laravel 5.7 and Nova v1.3.0. And no errors. Please check your installation.

**Comment by jafar690** [comment]
@Krato am using Laravel Framework 5.6.39

**Comment by Krato** [comment]
Should be the same. Sorry, try to activate Vue DevTools and check the error. Sorry, isn't possible without more details of the error.

Thanks
