### ISSUE TITLE
Post Processing

### ISSUE THREAD

**Issue by jphms** [InfinetyEs/Nova-Filemanager#56]
Hey there, I just went through the documentation twice and couldn't find any mention of it.
How does one hook into the saving method to perform some operations on the uploaded files, after they have been uploaded? Say to generate thumbnails or responsive image sizes.

**Comment by Krato** [comment]
That’s a good question. We’ll think about it 👌

**Comment by Krato** [comment]
@jphms Please check new version. You can add now jobs after upload files.
