### ISSUE TITLE
Laravel FLYSYSTEM - AWS S3 support

### ISSUE THREAD

**Issue by macolson** [InfinetyES/Nova-Filemanager#6]
We tried to use this file manager package together with AWS S3 but it is not working caused by errors by AWS s3 directory attributes / structure differences.

Is it planned to update the package to support AWS S3 in the near future?

**Comment by InfinetyES** [comment]
Yes. It's planned. I wil update this issue when released.

Regards

**Comment by Krato** [comment]
Please update to version 1.1.0, and check it.

**Comment by macolson** [comment]
Just had a quick test using S3, looking great. Thank you for making such a great Nova tool.
