### ISSUE TITLE
easy downloading

### ISSUE THREAD

**Issue by Dontorpedo** [InfinetyEs/Nova-Filemanager#61]
Very nice tool, but i would be nicer if the files where also downloadable in an easy way.. maybe just  an download link in the popup or shortcut symbols for download/delete in the files list view :)

**Comment by Krato** [comment]
@Dontorpedo you have a link input in the preview modal. You can use it to download the files. But we're opened to contributions.

**Comment by Krato** [comment]
Close due no updates
