### ISSUE TITLE
Error reading the folder. Please check your logs

### ISSUE THREAD

**Issue by marcreichel** [InfinetyEs/Nova-Filemanager#62]
When opening either the tool or the field modal I always get the above error. But there's nothing written to my logs. What causes this error? I didn't change the access rights.
And a few days ago it worked like a charm. But not anymore.
I would really like to provide more information. But that's all I got 😄

**Comment by htownson** [comment]
I had this issue as well after upgrading to Laravel 5.8 & Nova 2.

Nova now has a config file. If you haven't got it already, publish it with
`php artisan vendor:publish --tag=filemanager-config`

This fixed it for me.

**Comment by marcreichel** [comment]
Hm. Well, I've started the project with Laravel 5.8 & Nova 2 and also already published the config file. So that didn't fixed it for me 😅

**Comment by Krato** [comment]
Please, can you check the console errors in Development tools? Thanks

**Comment by marcreichel** [comment]
Well. Fixed it myself. I've overwritten the `nova-vendor`-route by mistake with a custom wildcard-route. Therefore a 404 error was thrown in the dev tools.
Fixed it by providing the following code in the `boot()`-method of my `RouteServiceProviders`:
```
Route::pattern('path', '^(?!nova|nova-api|nova-vendor).*$');
```

I think nova should register its routes before anything else and not after the custom routes to prevent collisions like this 🤷‍♂ But that's another topic and probably not for this thread 😄
