### ISSUE TITLE
Case Insensitive Filters?

### ISSUE THREAD

**Issue by marcreichel** [InfinetyEs/Nova-Filemanager#64]
Could you please make the extension filters case insensitive? Just uploaded a JPG-Image with ".JPG" extension instead of ".jpg" and it doesn't show up in my file selector with 'Images'-filter.
Of course I could add all the uppercase extensions to the array myself. But it would be easier to allow case insensitive file extensions out of the box I think.
I think there shouldn't be any side effects.

**Comment by Krato** [comment]
Yes. Next version will include that feature.

Thanks for ket us know! ;)
