### ISSUE TITLE
Breadcrumb on windows filesystem

### ISSUE THREAD

**Issue by ahmedkandel** [InfinetyEs/Nova-Filemanager#70]
Hello,

When using the Filemanager on windows machine/hosting, The breadcrumb paths are absolute due to the different directory separator:

![Screenshot_2](https://user-images.githubusercontent.com/28398523/62132419-5714ac80-b2dd-11e9-8f21-3bd6a8bae0de.png)

Thanks.

**Comment by Krato** [comment]
Merged!
