### ISSUE TITLE
How to validate file type of the field?

### ISSUE THREAD

**Issue by phuclh** [InfinetyEs/Nova-Filemanager#72]
How can I validate the file type when a user upload a file?

Right now, I only see filter to limit file display in filemanager but it still allows user upload all file types.

Thank you for this great package.

**Comment by Krato** [comment]
Good question @phuclh. We'll work on that. Thanks!

**Comment by Krato** [comment]
Hello @phuclh.

In the last release [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5) we add new methods to validate the uploads in the field. Please update to the new version and check the new [docs](https://infinetyes.github.io/Nova-Filemanager/2.5/using-the-field.html#validateupload) please.
