### ISSUE TITLE
How to make pagination?

### ISSUE THREAD

**Issue by sergey89d** [InfinetyEs/Nova-Filemanager#74]
She is sorely missed

**Comment by Krato** [comment]
No pagination for now #36

**Comment by progcode** [comment]
same here. your module doesn't write log files @Krato , so we don't know what's wrong. It would be good not to close the ticket but to deal with it

**Comment by Krato** [comment]
Sorry but I'm not focused on that package. And pagination is not on the roadmap.

If you want to include, as I told, you can make a PR.

Regards
