### ISSUE TITLE
Restricr folder on FileManager Tool

### ISSUE THREAD

**Issue by alejandrosanchez18** [InfinetyEs/Nova-Filemanager#79]
Is it possible to restrict folder? This is possible on the filemanager field but I need to do this on the filemanager tool. Each user have your personal folder

**Comment by Krato** [comment]
You can use a feature added in the last update (no in docs yet)

> Possibility to exclude Folders using `.hide` file.

**Comment by takifouhal** [comment]
> You can use a feature added in the last update (not in docs yet)
> 
> > Possibility to exclude Folders using `.hide` file.

but is there any way to restrict programmatically ? based on user id for instance
