### ISSUE TITLE
Cannot access Events fields

### ISSUE THREAD

**Issue by Lothindir** [InfinetyEs/Nova-Filemanager#80]
When firing events, the listener cannot access the events fields (ie 'path'). In the docs it's specified how to do it bur the events's fields are protected.

Am I missing the point ? Or is it an issue ?

[FileRemoved](https://github.com/InfinetyEs/Nova-Filemanager/blob/master/src/Events/FileRemoved.php)
[FileUploaded](https://github.com/InfinetyEs/Nova-Filemanager/blob/master/src/Events/FileUploaded.php)
[FolderRemoved](https://github.com/InfinetyEs/Nova-Filemanager/blob/master/src/Events/FolderRemoved.php)
[FolderUploaded](https://github.com/InfinetyEs/Nova-Filemanager/blob/master/src/Events/FolderUploaded.php)

**Comment by Krato** [comment]
Yes! Sorry. I will update soon 😪

**Comment by Krato** [comment]
@Lothindir check new version. Is fixed on [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5)
