### ISSUE TITLE
Styling Bug On CodeMirror

### ISSUE THREAD

**Issue by FutureFutureTo** [InfinetyEs/Nova-Filemanager#81]
Thanks for the great package!

Looks like the the codemirror theme being pulled into one of your vue templates has a height: 400px !important on it.

This overrides the Code field on Nova.

My fix was to add a custom css in the NovaServiceProvider in case anyone is wondering.

**Comment by Krato** [comment]
Thanks. Good to know

**Comment by Krato** [comment]
@FutureFutureTo this was fixed [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5). 

Thanks for your tip!
