### ISSUE TITLE
No modals showing

### ISSUE THREAD

**Issue by soliduskodas** [InfinetyEs/Nova-Filemanager#82]
Hello, 

"Create Folder" does not work. Nothing happen after click on this button. Same with file deleting. How to fix this? 

![delete](https://user-images.githubusercontent.com/26401925/66457260-a9f6a700-ea78-11e9-8903-6ccfb4a4720a.png)

![create_folder issue](https://user-images.githubusercontent.com/26401925/66457201-7ae03580-ea78-11e9-8e67-0d2bb74980f2.png)

**Comment by ianmcqueen** [comment]
@soliduskodas This appears to only be an issue with Nova v2.4.0 but downgrading to v2.3.1 fixes the issue.

**Comment by Krato** [comment]
Wow. I will check with Nova v2.4.0.

**Comment by XternalSoft** [comment]
hello, same problem with Nova 2.5.0

**Comment by stwinnie** [comment]
in Nova 2.5.0 everything is broken

source FileManager Field Modal already exists
source File Details already exists
source Create Folder already exists

**Comment by Fabio1988** [comment]
same issue. but also FileManagerField Modal in Nova for uploading in form-view doesn't work

**Comment by Krato** [comment]
We're trying to fix it. We used Nova Modals to load modals. Maybe we need to try things or change to another modal. Stay tuned.

**Comment by Fabio1988** [comment]
https://github.com/InfinetyEs/Nova-Filemanager/issues/89 modals within filemanager are working now I think. But in detail view of a model "open filemanager" doesn't work.

**Comment by u12206050** [comment]
I just reinstalled everything, but still have this issue. nova: 2.6.0

**Comment by Krato** [comment]
Hi guys! Please check the new release [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5). Should be fixed.

Check also the new [documentation](https://infinetyes.github.io/Nova-Filemanager/2.5/installation.html).
