### ISSUE TITLE
Delete and rename buttons in grid and list views

### ISSUE THREAD

**Issue by Fabio1988** [InfinetyEs/Nova-Filemanager#84]
hy :)

Is it possible to hide the buttons or to disable the functionality to delete and rename?
I can not allow to rename folder or file, because it's possible that it is used in a model as attribute.

eg. Post has attribute visual "images/test.jpg"... if I would rename folder "images" the attribute contains wrong content.

**Comment by Krato** [comment]
Hello @Fabio1988. The new release [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5) adds this new feature.

Now you can hide buttons as your own needs on the tool or even in the field. Check the new documentation.

[Options for the tool](https://infinetyes.github.io/Nova-Filemanager/2.5/using-the-tool.html#hidding-buttons).

[Methods for the field](https://infinetyes.github.io/Nova-Filemanager/2.5/using-the-field.html#hideuploadbutton)
