### ISSUE TITLE
Modals not working

### ISSUE THREAD

**Issue by FutureFutureTo** [InfinetyEs/Nova-Filemanager#85]
Laravel: 5.8
Nova: 2.3.1
Nova-Filemanager: 2.3

This is a strange bug - everything works fine locally, but on my production server, clicking anything that results in a pop-up modal does not work.

- CREATE FOLDER, DELETE IMAGE, EDIT IMAGE

- no console errors or anything. If anyone else is having this problem, some assistance would be greatly appreciated

**Comment by Krato** [comment]
Yes, after Nova update no modals. We're trying to fix it.
