### ISSUE TITLE
Modals not showing.

### ISSUE THREAD

**Issue by addgod** [InfinetyEs/Nova-Filemanager#86]
None of the modals are showing, with version 2.5.0 of nova, and 2.3.2 of file manager.

When transitions are wrapped in a panel, none of the modals are showing. It seems the transitions are build into the panel, if you look at the nova source code.

**Comment by Fabio1988** [comment]
https://github.com/InfinetyEs/Nova-Filemanager/issues/85

**Comment by Krato** [comment]
Fixed on [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5). Please check the last release and the new [documentation](https://infinetyes.github.io/Nova-Filemanager/2.5/installation.html).
