### ISSUE TITLE
Delete modal and Rename modal does not work inside filemanager field.

### ISSUE THREAD

**Issue by addgod** [InfinetyEs/Nova-Filemanager#88]
Inside the filemanager field, the delete modal and the rename modal, does not work.

I suspect is has todo with two modal being opened at the same time. It might also has something to do with a portal being open inside another portal. I cannot quite tell yet.

**Comment by Krato** [comment]
Fixed on [v2.5](https://github.com/InfinetyEs/Nova-Filemanager/releases/tag/2.5). Please check the last release and the new [documentation](https://infinetyes.github.io/Nova-Filemanager/2.5/installation.html).
